name = "client"
target = "javascript"
version = "1.0.0"

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
# shared = { path = "../shared" }
lustre = ">= 4.6.3 and < 5.0.0"
plinth = ">= 0.5.6 and < 1.0.0"
gleam_javascript = ">= 0.13.0 and < 1.0.0"
gleam_json = ">= 2.3.0 and < 3.0.0"
rsvp = ">= 1.0.1 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
lustre_dev_tools = ">= 1.6.5 and < 2.0.0"
