version: "3"
interval: 500ms

tasks:
  tailwindcss:
    dir: server
    cmds:
      - tailwindcss -i tailwind.css -o priv/static/assets/tailwind.min.css -w
  client:
    watch: true
    dir: client
    cmds:
      - gleam deps update
      - gleam build
      - echo "main();" >> build/dev/javascript/client/client.mjs
      - esbuild build/dev/javascript/client/client.mjs --bundle --minify --outfile=../server/priv/static/assets/client.min.mjs
    sources:
      - src/**/*
      - ../shared/src/**/*

  server:
    watch: true
    dir: server
    cmds:
      - gleam run
    sources:
      - src/**/*
      - ../shared/src/**/*
