version: "3"

tasks:
  clean:
    deps: [clean-client, clean-server, clean-shared]
  clean-client:
    dir: client
    cmds:
      - gleam clean
  clean-server:
    dir: server
    cmds:
      - gleam clean
  clean-shared:
    dir: shared
    cmds:
      - gleam clean
  tailwindcss:
    dir: client
    cmds:
      - tailwindcss -i tailwind.css -o priv/static/client.css -w
  client:
    dir: client
    cmds:
      - gleam run -m lustre/dev start --proxy-from=/api --proxy-to=http://localhost:3000/api
  server:
    dir: server
    cmds:
      - gleam run
