version: "3"

tasks:
  tailwindcss:
    dir: server
    cmds:
      - tailwindcss -i priv/static/assets/tailwind.css -o priv/static/assets/tailwind.min.css -w
  build-client:
    watch: true
    dir: client
    cmds:
      - gleam deps update
      - gleam build
      - echo "main();" >> build/dev/javascript/client/client.mjs
      - esbuild build/dev/javascript/client/client.mjs --bundle --minify --outfile=../server/priv/static/assets/client.min.mjs
    sources:
      - src/**/*.gleam
  server:
    dir: server
    cmds:
      - gleam run
